# site settings
title: Liguo Jiao
subtitle: project portfolio
email: liguo@jiao.co.nz
description: I’m an iOS developer with a passion for providing creative solutions to complex problem sets. <br/>
baseurl: ""
url: "https://portfolio.jiao.co.nz"
author: Liguo Jiao
city: Wellington
state: Wellington
country: New Zealand

# homepage tiles
tiles-source: posts
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/leandrojiew
github_url: https://github.com/iceman201
gitlab_url: https://gitlab.com/iceman201
linkedin_url: https://www.linkedin.com/in/liguojiaouc/
twitter_url: https://twitter.com/jiaoliguo

# build settings
markdown: kramdown

sass:
  style: compressed
google_analytics: UA-84796138-2
