# site settings
title: Liguo Jiao
subtitle: Project Portfolio
email: liguo@jiao.co.nz
description: I’m an iOS developer with a passion for providing creative solutions to complex problem sets. <br/>
logo: 'assets/images/LOGO2017.png'
baseurl: ""
url: "https://portfolio.jiao.co.nz"
author: Liguo Jiao
city: Auckland
area: Mt Wellington
zip_code: 1060
country: New Zealand

# homepage tiles
tiles-source: posts
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/leandrojiew
github_url: https://github.com/iceman201
gitlab_url: https://gitlab.com/iceman201
linkedin_url: https://www.linkedin.com/in/liguojiaouc/
twitter_url: https://twitter.com/jiaoliguo

# build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  syntax_highlighter: rouge

sass:
  style: compressed
google_analytics: UA-84796138-2
